version: '3'

services:
    frontend:
        image: etl-frontend
        ports:
            - 127.0.0.1:8080:80
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
    backend:
        image: etl-backend
        ports:
            - 127.0.0.1:3000:3000
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        depends_on:
            - db
        environment:
            - POSTGRES_DB=express-ts
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=express-ts
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
